version: "3.2"
services:
  maltrail:
    privileged: true
    image: index.docker.io/dnsc/jtan-maltrail
    container_name: maltrail
    hostname: "$SENSOR_LOCATION"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: on-failure
    depends_on:
      - filebeat
    network_mode: host
    environment:
      - TZ=UTC
    env_file:
      - .env

  filebeat:
    image: index.docker.io/dnsc/jtan-filebeat
    container_name: filebeat
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: on-failure
    network_mode: host
    environment:
      - TZ=UTC
    env_file:
      - .env