version: "3.2"
services:
  maltrail:
    privileged: true
    image: index.docker.io/dnsc/jtan-maltrail
    container_name: maltrail
    hostname: "$SENSOR_LOCATION"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    depends_on:
      - filebeat
    network_mode: host
    environment:
      - TZ=UTC
    env_file:
      - .env

  filebeat:
    image: index.docker.io/dnsc/jtan-filebeat
    container_name: filebeat
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    network_mode: host
    environment:
      - TZ=UTC
    env_file:
      - .env
  
  redis:
    image: "redis:6.2-alpine"
    container_name: redis
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    depends_on:
      - filebeat
    command: redis-server
    network_mode: host

  exporter:
    image: index.docker.io/dnsc/jtan-exporter
    container_name: exporter
    volumes:
      - ${CERTIFICATE}:/home/certs/cert.pem
      - /sys/firmware/devicetree/base/serial-number:/home/serial
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    network_mode: host
    env_file:
      - .env

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 3600
    environment:
      - WATCHTOWER_CLEANUP=true
