version: "3.2"
services:
  jtan-sensor-maltrail:
    privileged: true
    image: index.docker.io/dnsc/jtan-sensor-maltrail
    container_name: jtan-sensor-maltrail
    hostname: "$SENSOR_LOCATION"
    volumes:
      - logs:/logs
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    depends_on:
      - jtan-sensor-filebeat
    network_mode: host
    environment:
      - TZ=UTC
    env_file:
      - .env

  jtan-sensor-maltrail-web:
    image: index.docker.io/dnsc/jtan-sensor-maltrail-web
    container_name: jtan-sensor-maltrail-web
    volumes:
      - logs:/logs
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    depends_on:
      - jtan-sensor-maltrail
    network_mode: host
    environment:
      - TZ=UTC
    env_file:
      - .env

  jtan-sensor-filebeat:
    image: index.docker.io/dnsc/jtan-sensor-filebeat
    container_name: jtan-sensor-filebeat
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    network_mode: host
    environment:
      - TZ=UTC
    env_file:
      - .env
  
  jtan-sensor-redis:
    image: redis:6.2-alpine
    container_name: jtan-sensor-redis
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    depends_on:
      - jtan-sensor-filebeat
    command: redis-server
    network_mode: host

  jtan-sensor-exporter:
    image: index.docker.io/dnsc/jtan-sensor-exporter
    container_name: jtan-sensor-exporter
    volumes:
      - ${CERTIFICATE}:/home/certs/cert.pem
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    network_mode: host
    env_file:
      - .env

  jtan-sensor-log-rotate:
    image: index.docker.io/dnsc/jtan-sensor-log-rotate
    container_name: jtan-sensor-log-rotate
    volumes:
      - logs:/logs
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    env_file:
      - .env

  jtan-sensor-watchtower:
    image: containrrr/watchtower
    container_name: jtan-sensor-watchtower
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600
    environment:
      - WATCHTOWER_CLEANUP=true

volumes:
  logs:
    driver: local
